trigger:
  - master

pr:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: 'build'

  - task: DotNetCoreCLI@2
    displayName: Unit Tests
    inputs:
      command: 'test'